esphome:
  name: livingroom-d1-mini

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_fb_ssid
    password: !secret wifi_fb_password

captive_portal:
    
# Example configuration entry
sensor:
  - platform: dht
    pin: D4
    temperature:
      name: "Living Room DHT Temperature"
    humidity:
      name: "Living Room DHT Humidity"
    update_interval: 60s
  - platform: dallas
    address: 0xb1041733a098ff28
    name: "Living Room DS18B20 Temperature"

switch:
  - platform: gpio
    pin: GPIO5
    name: "Switch"
    inverted: false

dallas:
  - pin: GPIO4
