esphome:
  name: livingroom-d1-mini

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_fb_ssid
    password: !secret wifi_fb_password

captive_portal:
    
# Example configuration entry
sensor:
  - platform: dht
    pin: D4
    temperature:
      name: "Living Room DHT Temperature"
    humidity:
      name: "Living Room DHT Humidity"
    update_interval: 60s
  - platform: dallas
    address: 0xb1041733a098ff28
    name: "Living Room DS18B20 Temperature"
  # using I2C bus
  # - platform: bmp085
  #   temperature:
  #     name: "Living Room BMP180 Temperature"
  #   pressure:
  #     name: "Living Room BMP180 Pressure"
  #   update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: 14
    name: "PIR Sensor"
    device_class: motion

switch:
  - platform: gpio
    pin: GPIO5
    name: "Switch"
    inverted: false

dallas:
  - pin: GPIO4

# https://esphome.io/components/i2c.html
# https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/
# i2c:
#   # Wemos D1 mini default
#   # sda: 4 # GPIO4 (D2)
#   # scl: 5 # GPIO5 (D1)
#   sda: 12 # GPIO12 (D6)
#   scl: 13 # GPIO13 (D7)
#   scan: true
#   id: bus_a