esphome:
  name: livingroom3

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_fb_ssid
    password: !secret wifi_fb_password

captive_portal:
    
# Example configuration entry
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO4 # wemos d1 mini D2
    num_leds: 1
    name: "NeoPixel Light"

binary_sensor:
  - platform: gpio
    pin: 14 # wemos d1 mini D5
    name: "PIR Sensor"
    device_class: motion

# time:
#   - platform: sntp
#     id: my_time
