esphome:
  name: livingroom4

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_fb_ssid
    password: !secret wifi_fb_password

captive_portal:
    
# Example configuration entry
remote_receiver:
  pin:
    number: 14
    inverted: True
  dump: all

remote_transmitter:
  # pin: 1
  pin: 12
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: TV Power Button
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E040BF
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DF22DD
          nbits: 32
  - platform: template
    name: TV Mute button
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0F00F
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DF906F
          nbits: 32
  - platform: template
    name: TV Channel Up
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0F00F
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DF00FF
          nbits: 32
  - platform: template
    name: TV Channel Down
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E008F7
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DF807F
          nbits: 32
  - platform: template
    name: TV Volume Up
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0E01F
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DF40BF
          nbits: 32
  - platform: template
    name: TV Volume Down
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0D02F
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DFC03F
          nbits: 32
  - platform: template
    name: TV Input Source
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0807F
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DFD02F
          nbits: 32
  - platform: template
    name: TV One Button
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E020DF
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DF8877
          nbits: 32
  - platform: template
    name: TV Two Button
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0A05F
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DF48B7
          nbits: 32
  - platform: template
    name: TV Three Button
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0609F
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DFC837
          nbits: 32
  - platform: template
    name: TV Four Button
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E010EF
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DF28D7
          nbits: 32
  - platform: template
    name: TV Five Button
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0906F
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DFA857
          nbits: 32
  - platform: template
    name: TV Six Button
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E050AF
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DF6897
          nbits: 32
  - platform: template
    name: TV Seven Button
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E030CF
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DFE817
          nbits: 32
  - platform: template
    name: TV Eight Button
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0B04F
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DF18E7
          nbits: 32
  - platform: template
    name: TV Nine Button
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0708F
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DF9867
          nbits: 32
  - platform: template
    name: TV Zero Button
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E08877
          nbits: 32
      - remote_transmitter.transmit_lg:
          data: 0x20DF08F7
          nbits: 32

# output:
#   - platform: esp8266_pwm
#     # pin: D0
#     pin: 2
#     frequency: 1000 Hz
#     id: pwm_output

# light:
#   - platform: monochromatic
#     output: pwm_output
#     name: "Remocon Light"

# time:
#   - platform: sntp
#     id: my_time
