service: serverless-python
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: python3.8
  region: ${env:AWS_REGION}
  stage: ${opt:stage, "dev"}
  tracing:
    lambda: true
    apiGateway: true

plugins:
  - serverless-domain-manager
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
  customDomain:
    http:
      domainName: ${env:DOMAIN_NAME}
      stage: ${self:provider.stage}
      basePath: ''
      certificateName: ${env:CERTIFICATE_NAME}
      createRoute53Record: true
      createRoute53IPv6Record: true
      endpointType: 'regional'
      securityPolicy: tls_1_2

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
      # - http:
          path: /
          method: get
