esphome:
  name: livingroom2

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_fb_ssid
    password: !secret wifi_fb_password

captive_portal:
    
sensor:
  # using I2C bus
  - platform: bmp085
    temperature:
      name: "Living Room BMP180 Temperature"
    pressure:
      name: "Living Room BMP180 Pressure"
    update_interval: 10s

# https://esphome.io/components/i2c.html
# https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/
i2c:
  # Wemos D1 mini default
  sda: 4 # GPIO4 (D2)
  scl: 5 # GPIO5 (D1)
  # sda: 12 # GPIO12 (D6)
  # scl: 13 # GPIO13 (D7)
  scan: true
  id: bus_a

# time:
#   - platform: sntp
#     id: my_time
