esphome:
  name: kitchen

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_fb_ssid
    password: !secret wifi_fb_password

captive_portal:
    
# Example configuration entry
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO1 # ESP01 GPIO1
    num_leds: 17
    name: "Kitchen Light"

binary_sensor:
  - platform: gpio
    pin: 0 # ESP01 GPIO0
    name: "Kitchen PIR Sensor"
    device_class: motion

# time:
#   - platform: sntp
#     id: my_time
