#!/bin/bash

echo "AWS_REGION"; read AWS_REGION
echo "AWS_ACCESS_KEY_ID"; read AWS_ACCESS_KEY_ID
echo "AWS_SECRET_ACCESS_KEY"; read AWS_SECRET_ACCESS_KEY

gh secret set -e aws -f - <<EOF
AWS_REGION=$AWS_REGION
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
EOF
