version: '3.7'

services:
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: dynamodb
    hostname: dynamodb
    # restart: always
    volumes:
      -  ./data:/var/lib/dynamodb
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /var/lib/dynamodb/"
