service: serverless-telegram-bot
frameworkVersion: '3'
useDotenv: true

custom:
  tableNameUser: 'users-table-${sls:stage}'
  tableNameOrder: 'orders-table-${sls:stage}'
  tableNameTelegramWebhooks: 'telegram-webhooks-table-${sls:stage}'
  tableNameTelegramUser: 'telegram-users-table-${sls:stage}'
  tableNameWhatsappWebhooks: 'whatsapp-webhooks-table-${sls:stage}'
  tableNameWhatsappUser: 'whatsapp-users-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION, "ap-northeast-2"}
  stage: ${opt:stage, "dev"}
  deploymentBucket:
    # Name of an existing bucket to use (default: created by serverless)
    name: ${env:SERVERLESS_DEPLOYMENT_BUCKET}
    # On deployment, serverless prunes artifacts older than this limit (default: 5)
    maxPreviousDeploymentArtifacts: 5
    # Prevents public access via ACLs or bucket policies (default: false)
    # Note: the deployment bucket is not public by default. These are additional ACLs.
    blockPublicAccess: true
    # Skip the creation of a default bucket policy when the deployment bucket is created (default: false)
    # skipPolicySetup: true
    # Enable bucket versioning (default: false)
    # versioning: true
    # Server-side encryption method
    serverSideEncryption: AES256
    # For server-side encryption
    # sseKMSKeyId: arn:aws:kms:us-east-1:xxxxxxxxxxxx:key/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
    # For server-side encryption with custom keys
    # sseCustomerAlgorithim: AES256
    # sseCustomerKey: string
    # sseCustomerKeyMD5: md5sum
  tracing:
    lambda: true
    apiGateway: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 's3:*'
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            # - Fn::GetAtt: [ UsersTable, Arn ]
            # - Fn::GetAtt: [ OrdersTable, Arn ]
            # allow all tables in my account
            - 'arn:aws:dynamodb:${self:provider.region}:*:table/*'
  timeout: 25 # optional, in seconds, default is 6, API Gateway timeout is 30 seconds
  environment:
    STAGE: ${self:provider.stage}
    USERS_TABLE: ${self:custom.tableNameUser}
    ORDERS_TABLE: ${self:custom.tableNameOrder}

    TELEGRAM_WEBHOOKS_TABLE: ${self:custom.tableNameTelegramWebhooks}
    TELEGRAM_USERS_TABLE: ${self:custom.tableNameTelegramUser}
    
    WHATSAPP_WEBHOOKS_TABLE: ${self:custom.tableNameWhatsappWebhooks}
    WHATSAPP_USERS_TABLE: ${self:custom.tableNameWhatsappUser}

    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}

    TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'

  onOrderChange:
    handler: src/handlers/order.onOrderChange
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [ OrdersTable, StreamArn ]

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameUser}
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameOrder}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    TelegramWebhooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: updateId
            AttributeType: N
        KeySchema:
          - AttributeName: updateId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameTelegramWebhooks}
    TelegramUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: telegramUserId
            AttributeType: N
        KeySchema:
          - AttributeName: telegramUserId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameTelegramUser}
    WhatsappWebhooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: MessageSid
            AttributeType: S
        KeySchema:
          - AttributeName: MessageSid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameWhatsappWebhooks}
    WhatsappUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: whatsappUserId
            AttributeType: S
        KeySchema:
          - AttributeName: whatsappUserId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameWhatsappUser}
