esphome:
  name: pn532

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_fb_ssid
    password: !secret wifi_fb_password

captive_portal:
    
http_request:

# Example configuration entry
spi:
  clk_pin: 14
  mosi_pin: 13
  miso_pin: 12

pn532_spi:
  # cs_pin: 15 # D1 mini won't boot
  # https://community.home-assistant.io/t/d1-mini-wont-connect-to-wifi-after-adding-pn532-nfc-tag-reader/538612/2
  cs_pin: 5


# time:
#   - platform: sntp
#     id: my_time
