esphome:
  name: rc522

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

# ota:
#   password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_fb_ssid
    password: !secret wifi_fb_password

captive_portal:
    
# Example configuration entry
spi:
  clk_pin: 14
  mosi_pin: 13
  miso_pin: 12

rc522_spi:
  cs_pin: 15
  on_tag:
    then:
      - http_request.send:
          method: POST
          url: !secret nfc_tag_call_url
          headers:
            Content-Type: application/json
          json:
            tag: !lambda
              return x;
      - rtttl.play:
          # rtttl: 'siren:d=8,o=5,b=100:d,e,d,e,d,e,d,e'
          rtttl: 'two_short:d=4,o=5,b=100:16e6,16e6'

http_request:
  verify_ssl: false

output:
  - platform: esp8266_pwm
    pin: 5
    id: my_buzzer

rtttl:
  output: my_buzzer
  gain: 0.1

# time:
#   - platform: sntp
#     id: my_time
